from . import res_config_settings_changes
from . import operations_changes
from . import stock_picking_type_changes
from . import stock_picking_changes
from . import stock_picking_changes2
from . import res_partner_changes
from . import operation_type_component
from . import operation_cancel_reason
from . import surgitech_product_tool
from . import sale_order_changes
from . import product_line
from . import operation_stages
from . import stock_warehouse_changes
from . import stock_quant
from . import operation_tags
from . import intial_demand
from . import account_move_changes
# from . import account_payment_register
from . import waiting_list_patients