{
    'name': 'Medical Surgeries',
    'version': '1.1',
    'category': 'Sales',

    'summary': "Create New Operation with it's needs...",
    'sequence': 30,
    'description': """
Medical & Sales
====================
Create new Operation with name include hospital and add all it's data
    """,
    'depends': ['stock', 'calendar', 'base', 'mail', 'base_automation', 'product_pack','sale_stock','sale','surgi_partner','product','purchase','account','stock_account','surgi_inventory_changes'],
    'data': [
        'security/operations_security.xml',
        'security/ir.model.access.csv',
        'views/oprations_view.xml',
        'views/res_partner_changes.xml',
        'views/res_config_settings_changes_views.xml',
        'views/operation_cancel_reason_view.xml',
        'wizard/delivery_order_wizard_view.xml',
        'wizard/hanged_delivery_order_wizard.xml',
        'wizard/back_to_warehouse_wizard_view.xml',
        'wizard/hanged_back_to_warehouse_wizard.xml',
        'wizard/move_to_location_wizard_view.xml',
        'wizard/move_to_hanged_warehouse_wizard.xml',
        'wizard/cancell_operation_wizzard.xml',
        'wizard/cancell_stock_picking_wizzard.xml',
        ## 'wizard/hanged_stock_quant_invoice.xml',
        'wizard/hanged_stock_quant_so.xml',
        'views/stock_picking_type_views.xml',
        'views/stock_picking_changes.xml',
        'views/actions_of_warehouse_sequence.xml',
        'views/surgi_operation_sequence_view.xml',
        'views/operation_type_component.xml',
        'views/operation_sequence_view.xml',
        'views/sale_order_changes.xml',
        #'views/warehouse_coordinator_operation_view.xml',
        'views/stock_warehouse_changes.xml',
        'views/operation_tags_view.xml',
        'views/view_recon_operations.xml',
        'views/view_recon_operations_manager.xml',
        'views/view_recon_operation_need_approval.xml',
        'views/view_recon_operations_coordinator.xml',
        'views/view_trauma_operations_coordinator.xml',
        'views/view_trauma_operations.xml',
        'views/view_spine_operations.xml',
        'views/view_new_recon_operations.xml',
        'views/view_new_recon_operations_manager.xml',
        'views/stock_quant_list_view.xml',
        'report/stock_picking_report.xml',
        'report/report_products_discrepancies.xml',
        'views/hospital_surgeon_list_tree_view.xml',
        'views/account_invoice_changes.xml',
        #'views/account_payment_register_changes.xml',
        'views/view_hospital_activation.xml',
        'views/view_surgeon_confirmation_operations.xml',
        'views/view_tender_operations_admin.xml',
        'views/view_recon_operations_coordinator_tanta.xml',
        'views/view_recon_operations_coordinator_alex.xml',
        'views/view_recon_operations_coordinator_assuit.xml',
        'views/view_recon_operations_coordinator_sportes.xml',
        'views/waiting_list_patients.xml',
        'views/view_sports_operations.xml',
        #'views/view_bio_operations.xml',
        'views/view_sales_operations_coordinator.xml',
        'views/sales_area_manager_operation.xml',
        'views/view_biologic_operations.xml',
        'views/view_spine_operations_coordinator.xml',
        'views/view_biologic_operations_coordinator.xml',
        'views/view_extremets_operations.xml',
        'views/view_vagner_operations.xml',
        #'views/stock_picking_changes2.xml',
        ## 'report/report_deliveryslip.xml',
    ],

}
